[package]
name = "pgr2junit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-junit = "0.3"
patch = "0"
scanf = "*"
